---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiesta-app
  labels:
    app: fiesta-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiesta-front
  template:
    metadata:
      labels:
        app: fiesta-front
    spec:
      containers:
        - name: fiesta-app
          image: [REPRENDRE IP REGISTRY]:5000/fiesta:latest
          ports:
            - containerPort: 3000
          env:
          - name: MARIADB_IP
            value: [REPRENDRE IP MARIADB]
---
apiVersion: v1
kind: Service
metadata:
  name: fiesta-app-service
spec:
  type: LoadBalancer
  selector:
    app: fiesta-front
  ports:
    - name: http
      protocol: TCP
      port: 5001
      targetPort: 3000
---