---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiesta-app
  labels:
    app: fiesta-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiesta-front
  template:
    metadata:
      labels:
        app: fiesta-front
    spec:
      containers:
        - name: fiesta-app
          image: 10.42.108.45:5000/fiesta:2
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fiesta-app-service
spec:
  type: LoadBalancer
  selector:
    app: fiesta-front
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
---